import 'package:vid/actions/motions.dart';
import 'package:vid/motion/motion_function.dart';
import 'package:vid/motion/motion_type.dart';

extension MotionTypeExt on MotionType {
  /// The function that implements this motion
  MotionFunction get fn => switch (this) {
    .charNext => Motions.charNext,
    .charPrev => Motions.charPrev,
    .lineDown => Motions.lineDown,
    .lineUp => Motions.lineUp,
    .lineStart => Motions.lineStart,
    .lineEnd => Motions.lineEnd,
    .firstNonBlank => Motions.firstNonBlank,
    .wordNext => Motions.wordNext,
    .wordPrev => Motions.wordPrev,
    .wordEnd => Motions.wordEnd,
    .wordEndPrev => Motions.wordEndPrev,
    .wordCapNext => Motions.wordCapNext,
    .wordCapPrev => Motions.wordCapPrev,
    .wordCapEnd => Motions.wordCapEnd,
    .wordCapEndPrev => Motions.wordCapEndPrev,
    .fileStart => Motions.fileStart,
    .fileEnd => Motions.fileEnd,
    .findNextChar => Motions.findNextChar,
    .findPrevChar => Motions.findPrevChar,
    .findTillNextChar => Motions.findTillNextChar,
    .findTillPrevChar => Motions.findTillPrevChar,
    .paragraphNext => Motions.paragraphNext,
    .paragraphPrev => Motions.paragraphPrev,
    .sentenceNext => Motions.sentenceNext,
    .sentencePrev => Motions.sentencePrev,
    .sameWordNext => Motions.sameWordNext,
    .sameWordPrev => Motions.sameWordPrev,
    .searchNext => Motions.searchNext,
    .searchPrev => Motions.searchPrev,
    .matchBracket => Motions.matchBracket,
    .linewise => Motions.linewise,
  };

  /// The reversed motion type, or null if not reversible
  MotionType? get reversed => switch (this) {
    .charNext => .charPrev,
    .charPrev => .charNext,
    .lineDown => .lineUp,
    .lineUp => .lineDown,
    .wordNext => .wordPrev,
    .wordPrev => .wordNext,
    .wordEnd => .wordEndPrev,
    .wordEndPrev => .wordEnd,
    .wordCapNext => .wordCapPrev,
    .wordCapPrev => .wordCapNext,
    .wordCapEnd => .wordCapEndPrev,
    .wordCapEndPrev => .wordCapEnd,
    .fileStart => .fileEnd,
    .fileEnd => .fileStart,
    .findNextChar => .findPrevChar,
    .findPrevChar => .findNextChar,
    .findTillNextChar => .findTillPrevChar,
    .findTillPrevChar => .findTillNextChar,
    .paragraphNext => .paragraphPrev,
    .paragraphPrev => .paragraphNext,
    .sentenceNext => .sentencePrev,
    .sentencePrev => .sentenceNext,
    .sameWordNext => .sameWordPrev,
    .sameWordPrev => .sameWordNext,
    .searchNext => .searchPrev,
    .searchPrev => .searchNext,
    _ => null,
  };
}
