import 'package:vid/actions/motion_actions.dart';
import 'package:vid/motion/motion_function.dart';
import 'package:vid/motion/motion_type.dart';

extension MotionTypeExt on MotionType {
  /// The function that implements this motion
  MotionFunction get fn => switch (this) {
    .charNext => MotionActions.charNext,
    .charPrev => MotionActions.charPrev,
    .lineDown => MotionActions.lineDown,
    .lineUp => MotionActions.lineUp,
    .lineStart => MotionActions.lineStart,
    .lineEnd => MotionActions.lineEnd,
    .firstNonBlank => MotionActions.firstNonBlank,
    .wordNext => MotionActions.wordNext,
    .wordPrev => MotionActions.wordPrev,
    .wordEnd => MotionActions.wordEnd,
    .wordEndPrev => MotionActions.wordEndPrev,
    .wordCapNext => MotionActions.wordCapNext,
    .wordCapPrev => MotionActions.wordCapPrev,
    .wordCapEnd => MotionActions.wordCapEnd,
    .wordCapEndPrev => MotionActions.wordCapEndPrev,
    .fileStart => MotionActions.fileStart,
    .fileEnd => MotionActions.fileEnd,
    .findNextChar => MotionActions.findNextChar,
    .findPrevChar => MotionActions.findPrevChar,
    .findTillNextChar => MotionActions.findTillNextChar,
    .findTillPrevChar => MotionActions.findTillPrevChar,
    .paragraphNext => MotionActions.paragraphNext,
    .paragraphPrev => MotionActions.paragraphPrev,
    .sentenceNext => MotionActions.sentenceNext,
    .sentencePrev => MotionActions.sentencePrev,
    .sameWordNext => MotionActions.sameWordNext,
    .sameWordPrev => MotionActions.sameWordPrev,
    .searchNext => MotionActions.searchNext,
    .searchPrev => MotionActions.searchPrev,
    .matchBracket => MotionActions.matchBracket,
    .linewise => MotionActions.linewise,
  };

  /// The reversed motion type, or null if not reversible
  MotionType? get reversed => switch (this) {
    .charNext => .charPrev,
    .charPrev => .charNext,
    .lineDown => .lineUp,
    .lineUp => .lineDown,
    .wordNext => .wordPrev,
    .wordPrev => .wordNext,
    .wordEnd => .wordEndPrev,
    .wordEndPrev => .wordEnd,
    .wordCapNext => .wordCapPrev,
    .wordCapPrev => .wordCapNext,
    .wordCapEnd => .wordCapEndPrev,
    .wordCapEndPrev => .wordCapEnd,
    .fileStart => .fileEnd,
    .fileEnd => .fileStart,
    .findNextChar => .findPrevChar,
    .findPrevChar => .findNextChar,
    .findTillNextChar => .findTillPrevChar,
    .findTillPrevChar => .findTillNextChar,
    .paragraphNext => .paragraphPrev,
    .paragraphPrev => .paragraphNext,
    .sentenceNext => .sentencePrev,
    .sentencePrev => .sentenceNext,
    .sameWordNext => .sameWordPrev,
    .sameWordPrev => .sameWordNext,
    .searchNext => .searchPrev,
    .searchPrev => .searchNext,
    _ => null,
  };
}
