// EastAsianWidth-15.1.0.txt
// Autogenerated from https://www.unicode.org/Public/UNIDATA/EastAsianWidth.txt
bool eastAsianWidthSwitch(int codePoint) {
  switch (codePoint) {
    case >= 4352 && <= 4447:
      return true;
    case >= 8986 && <= 8987:
      return true;
    case 9001:
      return true;
    case 9002:
      return true;
    case >= 9193 && <= 9196:
      return true;
    case 9200:
      return true;
    case 9203:
      return true;
    case >= 9725 && <= 9726:
      return true;
    case >= 9748 && <= 9749:
      return true;
    case >= 9800 && <= 9811:
      return true;
    case 9855:
      return true;
    case 9875:
      return true;
    case 9889:
      return true;
    case >= 9898 && <= 9899:
      return true;
    case >= 9917 && <= 9918:
      return true;
    case >= 9924 && <= 9925:
      return true;
    case 9934:
      return true;
    case 9940:
      return true;
    case 9962:
      return true;
    case >= 9970 && <= 9971:
      return true;
    case 9973:
      return true;
    case 9978:
      return true;
    case 9981:
      return true;
    case 9989:
      return true;
    case >= 9994 && <= 9995:
      return true;
    case 10024:
      return true;
    case 10060:
      return true;
    case 10062:
      return true;
    case >= 10067 && <= 10069:
      return true;
    case 10071:
      return true;
    case >= 10133 && <= 10135:
      return true;
    case 10160:
      return true;
    case 10175:
      return true;
    case >= 11035 && <= 11036:
      return true;
    case 11088:
      return true;
    case 11093:
      return true;
    case >= 11904 && <= 11929:
      return true;
    case >= 11931 && <= 12019:
      return true;
    case >= 12032 && <= 12245:
      return true;
    case >= 12272 && <= 12287:
      return true;
    case 12288:
      return true;
    case >= 12289 && <= 12291:
      return true;
    case 12292:
      return true;
    case 12293:
      return true;
    case 12294:
      return true;
    case 12295:
      return true;
    case 12296:
      return true;
    case 12297:
      return true;
    case 12298:
      return true;
    case 12299:
      return true;
    case 12300:
      return true;
    case 12301:
      return true;
    case 12302:
      return true;
    case 12303:
      return true;
    case 12304:
      return true;
    case 12305:
      return true;
    case >= 12306 && <= 12307:
      return true;
    case 12308:
      return true;
    case 12309:
      return true;
    case 12310:
      return true;
    case 12311:
      return true;
    case 12312:
      return true;
    case 12313:
      return true;
    case 12314:
      return true;
    case 12315:
      return true;
    case 12316:
      return true;
    case 12317:
      return true;
    case >= 12318 && <= 12319:
      return true;
    case 12320:
      return true;
    case >= 12321 && <= 12329:
      return true;
    case >= 12330 && <= 12333:
      return true;
    case >= 12334 && <= 12335:
      return true;
    case 12336:
      return true;
    case >= 12337 && <= 12341:
      return true;
    case >= 12342 && <= 12343:
      return true;
    case >= 12344 && <= 12346:
      return true;
    case 12347:
      return true;
    case 12348:
      return true;
    case 12349:
      return true;
    case 12350:
      return true;
    case >= 12353 && <= 12438:
      return true;
    case >= 12441 && <= 12442:
      return true;
    case >= 12443 && <= 12444:
      return true;
    case >= 12445 && <= 12446:
      return true;
    case 12447:
      return true;
    case 12448:
      return true;
    case >= 12449 && <= 12538:
      return true;
    case 12539:
      return true;
    case >= 12540 && <= 12542:
      return true;
    case 12543:
      return true;
    case >= 12549 && <= 12591:
      return true;
    case >= 12593 && <= 12686:
      return true;
    case >= 12688 && <= 12689:
      return true;
    case >= 12690 && <= 12693:
      return true;
    case >= 12694 && <= 12703:
      return true;
    case >= 12704 && <= 12735:
      return true;
    case >= 12736 && <= 12771:
      return true;
    case 12783:
      return true;
    case >= 12784 && <= 12799:
      return true;
    case >= 12800 && <= 12830:
      return true;
    case >= 12832 && <= 12841:
      return true;
    case >= 12842 && <= 12871:
      return true;
    case 12880:
      return true;
    case >= 12881 && <= 12895:
      return true;
    case >= 12896 && <= 12927:
      return true;
    case >= 12928 && <= 12937:
      return true;
    case >= 12938 && <= 12976:
      return true;
    case >= 12977 && <= 12991:
      return true;
    case >= 12992 && <= 13055:
      return true;
    case >= 13056 && <= 13311:
      return true;
    case >= 13312 && <= 19903:
      return true;
    case >= 19968 && <= 40959:
      return true;
    case >= 40960 && <= 40980:
      return true;
    case 40981:
      return true;
    case >= 40982 && <= 42124:
      return true;
    case >= 42128 && <= 42182:
      return true;
    case >= 43360 && <= 43388:
      return true;
    case >= 44032 && <= 55203:
      return true;
    case >= 63744 && <= 64109:
      return true;
    case >= 64110 && <= 64111:
      return true;
    case >= 64112 && <= 64217:
      return true;
    case >= 64218 && <= 64255:
      return true;
    case >= 65040 && <= 65046:
      return true;
    case 65047:
      return true;
    case 65048:
      return true;
    case 65049:
      return true;
    case 65072:
      return true;
    case >= 65073 && <= 65074:
      return true;
    case >= 65075 && <= 65076:
      return true;
    case 65077:
      return true;
    case 65078:
      return true;
    case 65079:
      return true;
    case 65080:
      return true;
    case 65081:
      return true;
    case 65082:
      return true;
    case 65083:
      return true;
    case 65084:
      return true;
    case 65085:
      return true;
    case 65086:
      return true;
    case 65087:
      return true;
    case 65088:
      return true;
    case 65089:
      return true;
    case 65090:
      return true;
    case 65091:
      return true;
    case 65092:
      return true;
    case >= 65093 && <= 65094:
      return true;
    case 65095:
      return true;
    case 65096:
      return true;
    case >= 65097 && <= 65100:
      return true;
    case >= 65101 && <= 65103:
      return true;
    case >= 65104 && <= 65106:
      return true;
    case >= 65108 && <= 65111:
      return true;
    case 65112:
      return true;
    case 65113:
      return true;
    case 65114:
      return true;
    case 65115:
      return true;
    case 65116:
      return true;
    case 65117:
      return true;
    case 65118:
      return true;
    case >= 65119 && <= 65121:
      return true;
    case 65122:
      return true;
    case 65123:
      return true;
    case >= 65124 && <= 65126:
      return true;
    case 65128:
      return true;
    case 65129:
      return true;
    case >= 65130 && <= 65131:
      return true;
    case >= 65281 && <= 65283:
      return true;
    case 65284:
      return true;
    case >= 65285 && <= 65287:
      return true;
    case 65288:
      return true;
    case 65289:
      return true;
    case 65290:
      return true;
    case 65291:
      return true;
    case 65292:
      return true;
    case 65293:
      return true;
    case >= 65294 && <= 65295:
      return true;
    case >= 65296 && <= 65305:
      return true;
    case >= 65306 && <= 65307:
      return true;
    case >= 65308 && <= 65310:
      return true;
    case >= 65311 && <= 65312:
      return true;
    case >= 65313 && <= 65338:
      return true;
    case 65339:
      return true;
    case 65340:
      return true;
    case 65341:
      return true;
    case 65342:
      return true;
    case 65343:
      return true;
    case 65344:
      return true;
    case >= 65345 && <= 65370:
      return true;
    case 65371:
      return true;
    case 65372:
      return true;
    case 65373:
      return true;
    case 65374:
      return true;
    case 65375:
      return true;
    case 65376:
      return true;
    case >= 65504 && <= 65505:
      return true;
    case 65506:
      return true;
    case 65507:
      return true;
    case 65508:
      return true;
    case >= 65509 && <= 65510:
      return true;
    case >= 94176 && <= 94177:
      return true;
    case 94178:
      return true;
    case 94179:
      return true;
    case 94180:
      return true;
    case >= 94192 && <= 94193:
      return true;
    case >= 94208 && <= 100343:
      return true;
    case >= 100352 && <= 101119:
      return true;
    case >= 101120 && <= 101589:
      return true;
    case >= 101632 && <= 101640:
      return true;
    case >= 110576 && <= 110579:
      return true;
    case >= 110581 && <= 110587:
      return true;
    case >= 110589 && <= 110590:
      return true;
    case >= 110592 && <= 110847:
      return true;
    case >= 110848 && <= 110882:
      return true;
    case 110898:
      return true;
    case >= 110928 && <= 110930:
      return true;
    case 110933:
      return true;
    case >= 110948 && <= 110951:
      return true;
    case >= 110960 && <= 111355:
      return true;
    case 126980:
      return true;
    case 127183:
      return true;
    case 127374:
      return true;
    case >= 127377 && <= 127386:
      return true;
    case >= 127488 && <= 127490:
      return true;
    case >= 127504 && <= 127547:
      return true;
    case >= 127552 && <= 127560:
      return true;
    case >= 127568 && <= 127569:
      return true;
    case >= 127584 && <= 127589:
      return true;
    case >= 127744 && <= 127776:
      return true;
    case >= 127789 && <= 127797:
      return true;
    case >= 127799 && <= 127868:
      return true;
    case >= 127870 && <= 127891:
      return true;
    case >= 127904 && <= 127946:
      return true;
    case >= 127951 && <= 127955:
      return true;
    case >= 127968 && <= 127984:
      return true;
    case 127988:
      return true;
    case >= 127992 && <= 127994:
      return true;
    case >= 127995 && <= 127999:
      return true;
    case >= 128000 && <= 128062:
      return true;
    case 128064:
      return true;
    case >= 128066 && <= 128252:
      return true;
    case >= 128255 && <= 128317:
      return true;
    case >= 128331 && <= 128334:
      return true;
    case >= 128336 && <= 128359:
      return true;
    case 128378:
      return true;
    case >= 128405 && <= 128406:
      return true;
    case 128420:
      return true;
    case >= 128507 && <= 128511:
      return true;
    case >= 128512 && <= 128591:
      return true;
    case >= 128640 && <= 128709:
      return true;
    case 128716:
      return true;
    case >= 128720 && <= 128722:
      return true;
    case >= 128725 && <= 128727:
      return true;
    case >= 128732 && <= 128735:
      return true;
    case >= 128747 && <= 128748:
      return true;
    case >= 128756 && <= 128764:
      return true;
    case >= 128992 && <= 129003:
      return true;
    case 129008:
      return true;
    case >= 129292 && <= 129338:
      return true;
    case >= 129340 && <= 129349:
      return true;
    case >= 129351 && <= 129535:
      return true;
    case >= 129648 && <= 129660:
      return true;
    case >= 129664 && <= 129672:
      return true;
    case >= 129680 && <= 129725:
      return true;
    case >= 129727 && <= 129733:
      return true;
    case >= 129742 && <= 129755:
      return true;
    case >= 129760 && <= 129768:
      return true;
    case >= 129776 && <= 129784:
      return true;
    case >= 131072 && <= 173791:
      return true;
    case >= 173792 && <= 173823:
      return true;
    case >= 173824 && <= 177977:
      return true;
    case >= 177978 && <= 177983:
      return true;
    case >= 177984 && <= 178205:
      return true;
    case >= 178206 && <= 178207:
      return true;
    case >= 178208 && <= 183969:
      return true;
    case >= 183970 && <= 183983:
      return true;
    case >= 183984 && <= 191456:
      return true;
    case >= 191457 && <= 191471:
      return true;
    case >= 191472 && <= 192093:
      return true;
    case >= 192094 && <= 194559:
      return true;
    case >= 194560 && <= 195101:
      return true;
    case >= 195102 && <= 195103:
      return true;
    case >= 195104 && <= 196605:
      return true;
    case >= 196608 && <= 201546:
      return true;
    case >= 201547 && <= 201551:
      return true;
    case >= 201552 && <= 205743:
      return true;
    case >= 205744 && <= 262141:
      return true;
    default:
      return false;
  }
}

// length: 286
