import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:vid/grapheme/range_list.dart';

import 'range_list_extension.dart';

class EastAsianWidthParser {
  final wideRanges = RangeList([]);
  final url = 'https://unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt';
  String filename = '';
  String date = '';

  Future<void> load() async {
    final http.Response response = await http.get(Uri.parse(url));

    if (response.statusCode != 200) {
      throw Exception('Failed to download EastAsianWidth.txt');
    }

    final Iterable<String> lines = LineSplitter.split(response.body);

    filename = lines.take(1).single.replaceFirst('# ', '');
    date = lines.skip(1).take(1).single.replaceFirst('# ', '');

    for (var line in lines) {
      if (line.startsWith('#') || line.trim().isEmpty) continue;

      final parts = line.split(';');
      final range = parts[0].trim();
      final property = parts[1].split('#')[0].trim();

      if (property == 'W' || property == 'F') {
        if (range.contains('..')) {
          final bounds = range.split('..').map((e) => int.parse(e, radix: 16));
          wideRanges.addRange(IntRange(bounds.first, bounds.last));
        } else {
          final value = int.parse(range, radix: 16);
          wideRanges.addRange(IntRange.single(value));
        }
      }
    }
    // #  - The unassigned code points in the following blocks default to "W":
    // #         CJK Unified Ideographs Extension A: U+3400..U+4DBF
    // #         CJK Unified Ideographs:             U+4E00..U+9FFF
    // #         CJK Compatibility Ideographs:       U+F900..U+FAFF
    wideRanges.addRange(IntRange(0x3400, 0x4DBF));
    wideRanges.addRange(IntRange(0x4E00, 0x9FFF));
    wideRanges.addRange(IntRange(0xF900, 0xFAFF));
    // #  - All undesignated code points in Planes 2 and 3, whether inside or
    // #      outside of allocated blocks, default to "W":
    // #         Plane 2:                            U+20000..U+2FFFD
    // #         Plane 3:                            U+30000..U+3FFFD
    wideRanges.addRange(IntRange(0x20000, 0x2FFFD));
    wideRanges.addRange(IntRange(0x30000, 0x3FFFD));

    wideRanges.sortRanges();
  }

  void write() {
    final buffer = StringBuffer();
    buffer.writeln('''
// This file is generated by scripts/gen_east_asian_width.dart
// Do not edit this file manually
// Source: $url
// File: $filename
// $date
''');
    wideRanges.write(buffer, 'eastAsianWidth');
  }
}

void main() async {
  final parser = EastAsianWidthParser();
  await parser.load();
  parser.write();
}
