import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:vid/range_list.dart';

import 'range_list_extension.dart';

class EmojiDataParser {
  final RangeList emojiRanges = RangeList([]);
  final url = 'https://unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt';
  String filename = '';
  String date = '';

  Future<void> load() async {
    final response = await http.get(Uri.parse(url));

    if (response.statusCode != 200) {
      throw Exception('Failed to download emoji-data.txt');
    }
    final Iterable<String> lines = LineSplitter.split(response.body);

    filename = lines.take(1).single.replaceFirst('# ', '');
    date = lines.skip(1).take(1).single.replaceFirst('# ', '');

    for (var line in lines) {
      if (line.startsWith('#') || line.trim().isEmpty) continue;

      final parts = line.split(';');
      final range = parts[0].trim();
      if (range.contains('..')) {
        final bounds = range.split('..').map((e) => int.parse(e, radix: 16));
        emojiRanges.addRange(IntRange(bounds.first, bounds.last));
      } else {
        final value = int.parse(range, radix: 16);
        emojiRanges.addRange(IntRange.single(value));
      }
    }

    emojiRanges.sortRanges();
  }

  void write() {
    final buffer = StringBuffer();
    buffer.writeln('''
// This file is generated by scripts/gen_emoji_data.dart
// Do not edit this file manually
// Source: $url
// File: $filename
// $date
''');
    emojiRanges.write(buffer, 'emojiData');
  }
}

void main() async {
  final parser = EmojiDataParser();
  await parser.load();
  parser.write();
}
