import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

/// Generates lib/grapheme/width_table.dart — a 2-stage lookup table mapping
/// every Unicode code point to its terminal cell width (0, 1, or 2).
///
/// Based on the 3-stage technique described in:
///   https://here-be-braces.com/fast-lookup-of-unicode-properties/
/// (stage 3 is collapsed: width is 2 bits, stored directly in stage 2).
///
/// Width rules (baked in at generation time):
///   0 = zero-width: C0/C1 controls, DEL, Cf format, Mn/Me combining marks
///   2 = East Asian Wide/Fullwidth OR Emoji_Presentation
///   1 = everything else
///
/// Terminal-specific assumptions (per Ghostty semantics):
///   - widths clamp to a maximum of 2
///   - unassigned CJK ideograph blocks and planes 2-3 default to wide
///
/// Lookup: width = stage2[stage1[cp >> 8] + (cp & 0xFF)]

const _maxCodePoint = 0x10FFFF;
const _blockSize = 256; // one byte low-half split

class _Source {
  final String url;
  String filename = '';
  String date = '';
  _Source(this.url);

  Future<List<String>> fetchLines() async {
    final response = await http.get(Uri.parse(url));
    if (response.statusCode != 200) {
      throw Exception('Failed to download $url (${response.statusCode})');
    }
    final lines = LineSplitter.split(response.body).toList();
    filename = lines.first.replaceFirst('# ', '');
    date = lines[1].replaceFirst('# ', '');
    return lines;
  }
}

/// Parse a UCD range field like "1F600..1F64F" or "1F600" into (start, end).
(int, int) _parseRange(String field) {
  final range = field.trim();
  if (range.contains('..')) {
    final bounds = range.split('..');
    return (int.parse(bounds[0], radix: 16), int.parse(bounds[1], radix: 16));
  }
  final value = int.parse(range, radix: 16);
  return (value, value);
}

void _mark(List<int> width, int start, int end, int value) {
  for (int cp = start; cp <= end && cp <= _maxCodePoint; cp++) {
    width[cp] = value;
  }
}

Future<void> main() async {
  final width = List<int>.filled(_maxCodePoint + 1, 1);

  // --- Zero-width: C0, C1, DEL (hardcoded, stable across Unicode versions) ---
  _mark(width, 0x00, 0x1F, 0); // C0
  _mark(width, 0x7F, 0x9F, 0); // DEL + C1

  // --- Zero-width: Cf format, Mn/Me combining marks ---
  final gc = _Source(
    'https://unicode.org/Public/UCD/latest/ucd/extracted/DerivedGeneralCategory.txt',
  );
  for (final line in await gc.fetchLines()) {
    final clean = line.split('#').first.trim();
    if (clean.isEmpty) continue;
    final parts = clean.split(';');
    if (parts.length < 2) continue;
    final category = parts[1].trim();
    if (category != 'Cf' && category != 'Mn' && category != 'Me') continue;
    final (start, end) = _parseRange(parts[0]);
    _mark(width, start, end, 0);
  }

  // --- Wide: East Asian Width W/F ---
  final eaw = _Source(
    'https://unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt',
  );
  for (final line in await eaw.fetchLines()) {
    if (line.startsWith('#') || line.trim().isEmpty) continue;
    final parts = line.split(';');
    final property = parts[1].split('#')[0].trim();
    if (property != 'W' && property != 'F') continue;
    final (start, end) = _parseRange(parts[0]);
    _mark(width, start, end, 2);
  }
  // Unassigned code points defaulting to W (per EastAsianWidth.txt docs):
  _mark(width, 0x3400, 0x4DBF, 2); // CJK Unified Ideographs Extension A
  _mark(width, 0x4E00, 0x9FFF, 2); // CJK Unified Ideographs
  _mark(width, 0xF900, 0xFAFF, 2); // CJK Compatibility Ideographs
  _mark(width, 0x20000, 0x2FFFD, 2); // Plane 2
  _mark(width, 0x30000, 0x3FFFD, 2); // Plane 3

  // --- Wide: Emoji_Presentation (default-emoji code points) ---
  final emoji = _Source(
    'https://unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt',
  );
  for (final line in await emoji.fetchLines()) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
    final parts = trimmed.split(';');
    if (parts.length < 2) continue;
    if (parts[1].split('#')[0].trim() != 'Emoji_Presentation') continue;
    final (start, end) = _parseRange(parts[0]);
    _mark(width, start, end, 2);
  }

  // --- Build 2-stage table with 256-entry block dedup ---
  final stage1 = <int>[];
  final stage2 = <int>[];
  final blockIndex = <String, int>{}; // block contents -> stage2 offset

  for (
    int blockStart = 0;
    blockStart <= _maxCodePoint;
    blockStart += _blockSize
  ) {
    final block = width.sublist(blockStart, blockStart + _blockSize);
    final key = block.join(',');
    final offset = blockIndex.putIfAbsent(key, () {
      stage2.addAll(block);
      return stage2.length - _blockSize;
    });
    stage1.add(offset);
  }

  // --- Emit ---
  final out = StringBuffer();
  out.writeln('''
// This file is generated by scripts/gen_width_table.dart
// Do not edit this file manually
// Sources:
//   ${eaw.url}
//     ${eaw.filename} (${eaw.date})
//   ${emoji.url}
//     ${emoji.filename} (${emoji.date})
//   ${gc.url}
//     ${gc.filename} (${gc.date})
//
// 2-stage lookup of terminal cell width per code point.
// width = widthStage2[widthStage1[cp >> 8] + (cp & 0xFF)]
''');
  out.writeln('const widthStage1 = [');
  _writeInts(out, stage1);
  out.writeln('];\n');
  out.writeln('const widthStage2 = [');
  _writeInts(out, stage2);
  out.writeln('];');

  stdout.write(out);

  final kb = ((stage1.length * 2 + stage2.length) / 1024).toStringAsFixed(1);
  stderr.writeln('stage1: ${stage1.length} entries');
  stderr.writeln(
    'stage2: ${stage2.length} entries (${stage2.length ~/ _blockSize} unique blocks)',
  );
  stderr.writeln('approx size: $kb KB (stage1 as u16, stage2 as u8)');
}

void _writeInts(StringBuffer out, List<int> values) {
  const perLine = 16;
  for (int i = 0; i < values.length; i += perLine) {
    final chunk = values.sublist(
      i,
      i + perLine > values.length ? values.length : i + perLine,
    );
    out.writeln('  ${chunk.join(', ')},');
  }
}
