import 'dart:convert';

import 'package:http/http.dart' as http;

class EmojiSequencesParser {
  final List<List<int>> emojiSequences = [];
  final url = 'https://unicode.org/Public/emoji/latest/emoji-sequences.txt';
  String filename = '';
  String date = '';

  Future<void> load() async {
    final response = await http.get(Uri.parse(url));

    if (response.statusCode != 200) {
      throw Exception('Failed to download emoji-sequences.txt');
    }

    final Iterable<String> lines = LineSplitter.split(response.body);

    filename = lines.take(1).single.replaceFirst('# ', '');
    date = lines.skip(1).take(1).single.replaceFirst('# ', '');

    for (var line in lines) {
      // Remove comments and trim whitespace
      final cleanLine = line.split('#').first.trim();
      if (cleanLine.isEmpty) continue;

      // Parse the code point part
      final parts = cleanLine.split(';');
      if (parts.isEmpty) continue;

      final codePointPart = parts[0].trim();

      if (codePointPart.contains(' ')) {
        // Handle multi-codepoint sequence: e.g., "1F468 200D 1F469 200D 1F466"
        final codePoints = codePointPart
            .split(' ')
            .map((e) => int.parse(e, radix: 16))
            .toList();
        emojiSequences.add(codePoints); // Add only multi-codepoint sequences
      }
    }
  }

  void write() {
    final buffer = StringBuffer();
    buffer.writeln('''
// This file is generated by scripts/gen_emoji_sequences.dart
// Do not edit this file manually
// Source: $url
// File: $filename
// $date
''');
    buffer.writeln('final emojiSequences = [');
    for (var seq in emojiSequences) {
      buffer.writeln(
        '  [${seq.map((cp) => '0x${cp.toRadixString(16)}').join(', ')}],',
      );
    }
    buffer.writeln('];');
    buffer.writeln();
    print(buffer);
  }
}

void main() async {
  final parser = EmojiSequencesParser();
  await parser.load();
  parser.write();
}
