import 'dart:io';

import 'ucd_common.dart';

/// Generates lib/grapheme/emoji_sequences.dart — the list of multi-codepoint
/// emoji sequences from the Unicode emoji-sequences.txt data file.
///
/// Only multi-codepoint sequences are kept (the source also lists single
/// code points with a default emoji presentation; those are already handled
/// by the width table via Emoji_Presentation, so they would be redundant).
///
/// The list feeds the EmojiSequenceTrie in lib/grapheme/, which charWidth
/// uses to detect ZWJ emoji sequences (👩‍👩‍👦‍👦 = one emoji, width 2).

void main() async {
  final source = UcdSource(
    'https://unicode.org/Public/emoji/latest/emoji-sequences.txt',
  );
  final lines = await source.fetchLines();

  final sequences = <List<int>>[];
  for (final line in lines) {
    // Remove comments and trim whitespace
    final cleanLine = line.split('#').first.trim();
    if (cleanLine.isEmpty) continue;

    final codePointPart = cleanLine.split(';')[0].trim();

    // Keep only multi-codepoint sequences: "1F468 200D 1F469 200D 1F466"
    if (!codePointPart.contains(' ')) continue;
    sequences.add(
      codePointPart.split(' ').map((e) => int.parse(e, radix: 16)).toList(),
    );
  }

  final out = StringBuffer();
  out.writeln('''
// This file is generated by scripts/gen_emoji_sequences.dart
// Do not edit this file manually
// Source: ${source.url}
// File: ${source.description}
''');
  out.writeln('const emojiSequences = [');
  for (final seq in sequences) {
    out.writeln(
      '  [${seq.map((cp) => '0x${cp.toRadixString(16)}').join(', ')}],',
    );
  }
  out.writeln('];');
  out.writeln();

  stdout.write(out);

  stderr.writeln('sequences: ${sequences.length}');
  stderr.writeln('source: ${source.description}');
}
